# Generated by Django 4.2.7 on 2024-05-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adventure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("world", models.ImageField(default="", upload_to="images/")),
                ("hull_points", models.JSONField(blank=True, null=True)),
                ("world_points", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song", models.CharField(max_length=1255, null=True)),
                ("song_index", models.JSONField(blank=True, null=True)),
                ("changed_song", models.CharField(max_length=100, null=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song",
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inhabitant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inhabitants", models.JSONField(blank=True, null=True)),
                ("bearers", models.IntegerField(null=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inhabitant",
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guard",
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fence", models.ImageField(default="", upload_to="images/")),
                ("fence_neighbors", models.JSONField(blank=True, null=True)),
                ("neighbors_matrix", models.JSONField(blank=True, null=True)),
                (
                    "fence_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fence",
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factory", models.JSONField(blank=True, null=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factory",
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField()),
                ("person_id", models.IntegerField()),
                ("stop_points", models.JSONField(blank=True, null=True)),
                ("songs", models.JSONField(blank=True, null=True)),
                ("image", models.ImageField(default="", upload_to="images/")),
                (
                    "guard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="flatworld.guard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.JSONField(blank=True, null=True)),
                ("coded_song", models.CharField(max_length=100, null=True)),
                ("uncoded_song", models.CharField(max_length=100, null=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code",
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
    ]
