# Generated by Django 4.2.7 on 2024-04-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatworld", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adventure",
            old_name="fence_build_cost",
            new_name="fence_cost",
        ),
        migrations.AddField(
            model_name="adventure",
            name="fence",
            field=models.ImageField(default="", upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="adventure",
            name="world",
            field=models.ImageField(default="", upload_to="images/"),
        ),
    ]
