# Generated by Django 4.2.7 on 2024-05-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flatworld",
            "0002_rename_fence_build_cost_adventure_fence_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="adventure",
            name="world_points",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
    ]
