# Generated by Django 4.2.7 on 2024-05-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flatworld", "0003_adventure_world_points"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adventure",
            old_name="hull",
            new_name="hull_points",
        ),
    ]
