# Generated by Django 4.2.7 on 2024-05-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatworld", "0004_rename_hull_adventure_hull_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adventure",
            name="fence_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="adventure",
            name="hull_points",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="adventure",
            name="world_points",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
