# Generated by Django 4.2.7 on 2024-05-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatworld", "0005_alter_adventure_fence_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventure",
            name="bearers",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adventure",
            name="changed_song",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="adventure",
            name="code",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adventure",
            name="coded_song",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="adventure",
            name="factory",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adventure",
            name="guards",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adventure",
            name="schedule",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adventure",
            name="song",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
