# Generated by Django 4.2.7 on 2024-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flatworld",
            "0006_adventure_bearers_adventure_changed_song_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="adventure",
            name="inhabitants",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
