# Generated by Django 4.2.7 on 2024-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatworld", "0007_adventure_inhabitants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adventure",
            name="bearers",
            field=models.IntegerField(null=True),
        ),
    ]
