# Generated by Django 4.2.7 on 2024-05-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatworld", "0008_alter_adventure_bearers"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventure",
            name="filename",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
