# Generated by Django 4.2.7 on 2024-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatworld", "0010_remove_adventure_filename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adventure",
            name="world_points",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
