# Generated by Django 4.2.7 on 2024-05-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatworld", "0012_adventure_fence_neighbors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adventure",
            name="song",
            field=models.CharField(max_length=1255, null=True),
        ),
    ]
