# Generated by Django 4.2.7 on 2024-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flatworld", "0013_alter_adventure_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventure",
            name="song_index",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
