# Generated by Django 4.2.7 on 2024-05-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flatworld", "0015_adventure_uncoded_song"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adventure",
            name="bearers",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="changed_song",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="code",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="coded_song",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="factory",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="fence",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="fence_cost",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="fence_neighbors",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="guards",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="inhabitants",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="schedule",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="song",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="song_index",
        ),
        migrations.RemoveField(
            model_name="adventure",
            name="uncoded_song",
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song", models.CharField(max_length=1255, null=True)),
                ("song_index", models.JSONField(blank=True, null=True)),
                ("changed_song", models.CharField(max_length=100, null=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inhabitant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inhabitants", models.JSONField(blank=True, null=True)),
                ("bearers", models.IntegerField(null=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guards", models.JSONField(blank=True, null=True)),
                ("schedule", models.JSONField(blank=True, null=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fence", models.ImageField(default="", upload_to="images/")),
                ("fence_neighbors", models.JSONField(blank=True, null=True)),
                (
                    "fence_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("factory", models.JSONField(blank=True, null=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.JSONField(blank=True, null=True)),
                ("coded_song", models.CharField(max_length=100, null=True)),
                ("uncoded_song", models.CharField(max_length=100, null=True)),
                (
                    "adventure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flatworld.adventure",
                    ),
                ),
            ],
        ),
    ]
