# Generated by Django 4.2.7 on 2024-05-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flatworld", "0016_remove_adventure_bearers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fence",
            name="neighbors_matrix",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="code",
            name="adventure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code",
                to="flatworld.adventure",
            ),
        ),
        migrations.AlterField(
            model_name="factory",
            name="adventure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factory",
                to="flatworld.adventure",
            ),
        ),
        migrations.AlterField(
            model_name="fence",
            name="adventure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fence",
                to="flatworld.adventure",
            ),
        ),
        migrations.AlterField(
            model_name="guard",
            name="adventure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guard",
                to="flatworld.adventure",
            ),
        ),
        migrations.AlterField(
            model_name="inhabitant",
            name="adventure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inhabitant",
                to="flatworld.adventure",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="adventure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="song",
                to="flatworld.adventure",
            ),
        ),
    ]
